name: job_boarder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get:
  get_storage:
  freezed_annotation:
  dartz:
  json_serializable:
  rxdart:
  dio: ^4.0.6
  path_provider: ^2.0.2
  permission_handler: ^8.0.0+2
  animate_do: ^2.1.0
  auto_animated: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_form_builder: ^7.2.1
  loading_overlay: ^0.3.0
  json_annotation: ^4.5.0
  onboarding: ^3.1.0
  syncfusion_flutter_pdfviewer: ^20.3.57
  file_picker: ^5.2.2
  intl: ^0.17.0
  flutter_widget_from_html: ^0.9.0+1
  image_picker: ^0.8.5+3
  flutter_otp_text_field: ^1.1.1
  multi_select_flutter: ^4.1.3

dev_dependencies:
  build_runner: 
  freezed: 
  flutter_launcher_icons: ^0.11.0
  
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
